### PR TITLE
Filter user account's address from quick connect suggestions

### LINKED ISSUE #598: Quick Connect shows client account's address
## Describe the bug
It is possible that the PFS suggests the address of the user's raiden account. The Quick Connect dialog does not filter it. So it is possible that it is shown in the suggested connections and when it would get selected the client API would return an error. The address of the running raiden client should get filtered from the Quick Connect dialog.

## System
- Raiden: v1.1.1.dev445+g35ef6b589
- WebUI: v1.1.1
- Environment: development
- Network: Görli
- User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0

### PR DESCRIPTION
**Pull request by manuelwedler**
Fixes #598 

The Quick Connect dialog could show the address of the user account as a suggestion for creating a channel. This PR filters the suggestions that are returned from the PFS by the user account's address.

### CODE REVIEW

File: src/app/components/quick-connect-dialog/quick-connect-dialog.component.ts [hunk 1]
```diff
@@ -160,14 +153,16 @@ export class QuickConnectDialogComponent implements OnInit, OnDestroy {
...
-                    )
+                    suggestions.filter((suggestion) => {
+                        const channelExisting = !!channels.find(
+                            (channel) =>
+                                channel.partner_address === suggestion.address
+                        );
+                        const isOwnAddress =
+                            suggestion.address ===
+                            this.raidenService.raidenAddress;
+                        return !channelExisting && !isOwnAddress;
```
Comment (weilbith) [inline src/app/components/quick-connect-dialog/quick-connect-dialog.component.ts:164]: No comment but compliment: I like that you use descriptive names for the boolean expressions here. This makes the code very clean and super easy to read like a book. Good job! 👍🏾 
(just close the conversation)

**Review by weilbith — APPROVED** [review]
✔️

File: src/app/components/quick-connect-dialog/quick-connect-dialog.component.ts (hunk 1 above)
Comment (manuelwedler) [reply src/app/components/quick-connect-dialog/quick-connect-dialog.component.ts:164]: That's also precious feedback, thank you :smiley:
