### PR TITLE
Handle unset PFS in QuickConnectDialogComponent

### LINKED ISSUE #580: New Quick Connect does not handle unset PFS case
## Describe the bug
In case the private routing mode is used, the `/settings` endpoint returns `null` for the `pathfinding_service_address`.
When opening the Quick Connect dialog then the spinner keeps spinning forever.

## Expected behavior
The user should see a message telling them that quick connect cannot be used with private routing mode.

## System:
- WebUI: v1.1.0

### PR DESCRIPTION
**Pull request by manuelwedler**
closes #580

### CODE REVIEW

File: src/app/components/quick-connect-dialog/quick-connect-dialog.component.ts [hunk 1]
```diff
@@ -46,6 +53,7 @@ export class QuickConnectDialogComponent implements OnInit, OnDestroy {
     suggestions: SuggestedConnection[] = [];
     loading = false;
     pfsError = false;
+    noPfs = false;
```
Comment (karlb) [inline src/app/components/quick-connect-dialog/quick-connect-dialog.component.ts:56]: Negated variables can cause awkward comparisons. `if (PfsConfigured)` is usually easier to read than `if (!noPfs).`

File: src/app/components/quick-connect-dialog/quick-connect-dialog.component.html [hunk 2]
```diff
@@ -40,9 +40,19 @@
...
+                class="error"
+                fxLayoutAlign="center"
+            >
                 Could not fetch any suggestions
             </div>
         </ng-template>
+        <ng-template #no_pfs>
+            <div class="error" fxLayoutAlign="center">
+                You cannot use Quick Connect because you are using the private
+                routing mode
```
Comment (karlb) [inline src/app/components/quick-connect-dialog/quick-connect-dialog.component.html:54]: This is correct, but the relationship between routing mode and PFS configuration could change. Maybe it is safer to say something like "Quick Connect requires a pathfinding service, but no such service is configured"? This makes it less obvious what the user has to change to get QC working, though.

**Review by karlb — APPROVED** [review]

File: src/app/components/quick-connect-dialog/quick-connect-dialog.component.html (hunk 2 above)
Comment (manuelwedler) [reply src/app/components/quick-connect-dialog/quick-connect-dialog.component.html:54]: Exactly, I wanted it to make it more obvious what needs to be changed. But I'll go with your way now, as someone who configures the routing mode would probably know what they do.
